import { PDFArray, PDFDict, PDFDocument, PDFName, PDFObject, PDFRawStream } from '@cantoo/pdf-lib';

function representation(object: PDFObject): string {
  if (object instanceof PDFArray) return JSON.stringify(object.asArray().map(representation));
  if (object instanceof PDFDict) return JSON.stringify(object.entries().map(([key, value]) => [key.toString(), representation(value)]).sort(([a], [b]) => a.localeCompare(b)));
  return object.toString();
}

export function snapshotDocument(doc: PDFDocument) {
  // XRef and ObjStm are serialization containers, regenerated by the writer.
  // Parsed members of each ObjStm remain individually checked below.
  return doc.context.enumerateIndirectObjects().filter(([, object]) => !(object instanceof PDFRawStream && ['/XRef', '/ObjStm'].includes(String(object.dict.get(PDFName.of('Type')))))).map(([ref, object]) => ({
    ref,
    value: representation(object instanceof PDFRawStream ? object.dict : object),
    bytes: object instanceof PDFRawStream ? object.contents.slice() : undefined,
  }));
}

export function matchesSnapshot(snapshot: ReturnType<typeof snapshotDocument>, doc: PDFDocument): boolean {
  return snapshot.every(({ ref, value, bytes }) => {
    const object = doc.context.lookup(ref);
    if (!object || representation(object instanceof PDFRawStream ? object.dict : object) !== value) return false;
    if (!bytes) return !(object instanceof PDFRawStream);
    return object instanceof PDFRawStream && object.contents.length === bytes.length && bytes.every((byte, index) => byte === object.contents[index]);
  });
}
